### ISSUE TITLE
在运行scrapy爬取信息时报错ERROR: Spider error processing 跪求大佬解答

### ISSUE THREAD

**Issue by Thomas-YXW** [Aqua-Dream/Tieba_Spider#10]
![error](https://user-images.githubusercontent.com/35752361/50158340-d507e280-030e-11e9-84c2-891bedf7d2df.png)

**Comment by Aqua-Dream** [comment]
能否提供一下出错的帖子地址以及文本内容?

**Comment by Thomas-YXW** [comment]
# -*- coding: utf-8 -*-
#  stock.py
import scrapy
import re
from urllib import parse


class StockSpider(scrapy.Spider):
    name = 'stock'
    allowed_domains = ['pycs.greedyai.com']
    start_urls = ['http://pycs.greedyai.com/']

    def parse(self, response):
        post_urls = response.xpath("//a/@href").extract()
        print(post_urls)
        for post_url in post_urls:
            # print(parse.urljoin(response.url, post_url))
            yield scrapy.Request(url=parse.urljoin(response.url, post_url), callback=self.parse_detail,
                                 dont_filter=True)
        pass

    def parse_detail(self, response):
        # 董事会成员姓名
        # names = self.get_tc(response)
        # 抓取性别信息
        sexs = self.get_sex(response)
        # # 抓取年龄信息
        # ages = self.get_age(response)
        # # 股票代码
        # codes = self.get_code(response)
        # # 职位信息
        # leaders = self.get_leader(response, len(names))

        pass

    def get_tc(self, response):
        tc_names = []
        tc_name = response.xpath('//*[@id=\"ml_001\"]/table/tbody/tr[1]/td[1]/a/text()').extract()
        tc_names.append(tc_name)
        return tc_names

    def get_sex(self, response):
        infos = response.xpath("//*[@class=\"intor\"]/text()").extract()
        sex_list = []
        for info in infos:
            try:
                sex = re.findall("[男|女]", info)[0]
                sex_list.append(sex)
            except IndexError:
                continue
        return sex_list

    def get_age(self, response):
        infos = response.xpath("//*[@class=\"intor\"]/text()").extract()
        age_list = []
        for info in infos:
            try:
                age = re.findall("\d+", info)[0]
                age_list.append(age)
            except IndexError:
                continue
        return age_list

    def get_code(self, response):
        infos = response.xpath("/html/body/div[3]/div[1]/div[2]/div[1]/h1/a/@title").extract()
        code_list = []
        for info in infos:
            code = re.findall("\d+", info)[0]
            code_list.append(code)

        return code_list

    def get_leader(self, response, length):
        tc_leaders = response.xpath("//*[@class=\"tl\"]/text()").extract()
        tc_leaders = tc_leaders[0:length]
        return tc_leaders

**Comment by Thomas-YXW** [comment]
# main.py
from scrapy.cmdline import execute

import  sys
import os

sys.path.append(os.path.dirname(os.path.abspath(__file__)))
# execute(["scrapy","crawl","tonghuashun"])
execute(["scrapy","crawl","stock"])

**Comment by Thomas-YXW** [comment]
from scrapy.cmdline import execute

import  sys
import os

sys.path.append(os.path.dirname(os.path.abspath(__file__)))
execute(["scrapy","crawl","stock"])

**Comment by Thomas-YXW** [comment]
# main.py
from scrapy.cmdline import execute

import  sys
import os

sys.path.append(os.path.dirname(os.path.abspath(__file__)))
execute(["scrapy","crawl","stock"])

**Comment by Thomas-YXW** [comment]
我爬取的地址是http://pycs.greedyai.com/      
希望您解答！

**Comment by Aqua-Dream** [comment]
你发错地方了，这个项目是贴吧的爬取工具。你不妨去相关scrapy的论坛或者社区提问，此处不讨论该问题，抱歉。
