### ISSUE TITLE
为什么爬取数据的时候，内存占用会越来越大呢？应该要怎么优化？

### ISSUE THREAD

**Issue by LCG22** [Aqua-Dream/Tieba_Spider#13]
如题

**Comment by Aqua-Dream** [comment]
我之前爬两小时都没问题，应该不会内存越来越大的。

**Comment by LCG22** [comment]
> 我之前爬两小时都没问题，应该不会内存越来越大的。

会的，我爬了大概十六万条数据后，内存占用就差不多有7G了。代码我都是没有修改的

**Comment by Aqua-Dream** [comment]
你确定内存是爬虫脚本进程占用的吗？我没有办法排查，建议你每次只爬一部分，即设定参数-p。

**Comment by LCG22** [comment]
> 你确定内存是爬虫脚本进程占用的吗？我没有办法排查，建议你每次只爬一部分，即设定参数-p。

是爬虫占用的，因为我把其他的各种软件都关掉了的

**Comment by Aqua-Dream** [comment]
不是关掉其他软件就行，你得看看具体是哪个进程占了多少内存，linux下"top"，windows下打开任务管理器

**Comment by LCG22** [comment]
> 不是关掉其他软件就行，你得看看具体是哪个进程占了多少内存，linux下"top"，windows下打开任务管理器

占用内存最多的进程是 Python，而我除了跑爬虫，是没有跑其他的程序的

**Comment by Aqua-Dream** [comment]
那我真不清楚了，readme里也有写，我之前爬的回复数最多达120W条，也没出现问题，所以我倾向于是你那边数据库或者磁盘的问题。
