### ISSUE TITLE
请教一下大佬，为啥自己设置了user-agent就爬取不到数据了

### ISSUE THREAD

**Issue by shimachao** [Aqua-Dream/Tieba_Spider#14]
我试了一下，如果自己将user-agent设置为真实浏览器的ua，就会出现第一个请求被重定向到一个奇怪的地址，然后就爬不到数据了。

**Comment by Aqua-Dream** [comment]
在哪里设UA，具体设成什么，重定向的地址是什么，~~我一问三不知~~
