### ISSUE TITLE
在哪里设UA，具体设成什么，重定向的地址是什么，~~我一问三不知~~

### ISSUE THREAD

**Issue by shimachao** [Aqua-Dream/Tieba_Spider#15]
在哪里设UA，具体设成什么，重定向的地址是什么，~~我一问三不知~~

_Originally posted by @Aqua-Dream in https://github.com/Aqua-Dream/Tieba_Spider/issues/14#issuecomment-472864508_

就是自己加了一个downloadMiddleware，在它的process_request方法中调用request.headers.setdefault设置了User-Agent。被重定向到一个百度搜索页面

**Comment by Aqua-Dream** [comment]
可能你UA填的不对吧，我也不好验证。你为什么要加UA？
