### ISSUE TITLE
可以把三张表的内容合在一起吗，我想直接入kafka

### ISSUE THREAD

**Issue by ZQbd** [Aqua-Dream/Tieba_Spider#18]

**Comment by Aqua-Dream** [comment]
结构不一样啊

**Comment by ZQbd** [comment]
> 结构不一样啊

我的意思数据组合成一条，就和三张表join后的效果一样。
但是我想爬取完就组合在一起，然后直接输出到kafka

**Comment by ZQbd** [comment]
> > 结构不一样啊
> 
> 我的意思数据组合成一条，就和三张表join后的效果一样。
> 但是我想爬取完就组合在一起，然后直接输出到kafka

数据类似于这种：
![image](https://user-images.githubusercontent.com/43110242/61120572-dc235780-a4cf-11e9-8d05-e4ceaed6d9f8.png)
你能帮忙看下吗，我试着改下了你的代码，没成功，之前没搞过python。。。

**Comment by Aqua-Dream** [comment]
你爬完之后写条sql自己join就好了吧？这都是primary-foreign key join应该不用多久。

**Comment by ZQbd** [comment]
> 你爬完之后写条sql自己join就好了吧？这都是primary-foreign key join应该不用多久。

我的意思是我不想存到mysql，我要直接组合好 入kafka，然后我会接流式处理框架分析。

**Comment by Aqua-Dream** [comment]
> > 你爬完之后写条sql自己join就好了吧？这都是primary-foreign key join应该不用多久。
> 
> 我的意思是我不想存到mysql，我要直接组合好 入kafka，然后我会接流式处理框架分析。

你可以看看`pipeline.py`里面的几个`insert_xxx`函数，这些函数会处理搜集到的单条信息，然后整理成sql语句插入。不过回复和帖子信息是分开的，没法直接组到一起。
