### ISSUE TITLE
http://tieba.baidu.com/p/5069506634 无法爬到

### ISSUE THREAD

**Issue by CharrzookA** [Aqua-Dream/Tieba_Spider#20]
又试了其他几个网站，都可以完成，唯独这个

**Comment by Aqua-Dream** [comment]
是thread里也没有吗？你的爬虫命令是怎么写的？

**Comment by shitianshiwa** [comment]
旧版贴吧的贴子（http）确实和现在的贴吧的贴子（https）有各种细微的差别，只能具体去针对了。。！折腾贴吧扩展javascript脚本+继续更新别人的指定贴吧贴子全获取python3爬虫有感。

**Comment by Aqua-Dream** [comment]
更新了一下，可以再试试
