### ISSUE TITLE
AttributeError: module 'config' has no attribute 'config'

### ISSUE THREAD

**Issue by nolczak** [Aqua-Dream/Tieba_Spider#23]
你好！我正在试图用你的Scraper 但是我总是碰到这个问题：
> File "/Users/.../PycharmProjects/BD_scraper/Tieba_Spider/tieba/commands/run.py", line 59, in run
>     cfg = config.config()
> AttributeError: module 'config' has no attribute 'config'

你可以帮我解决吗？
感谢你！

**Comment by nolczak** [comment]
I resolved this by deleting the 'config' module, which is not required

**Comment by Aqua-Dream** [comment]
scrapy run的命令执行时当前文件夹应在最上一层(即和README在同一目录)。否则应该运行不了吧？

你运行的时候当前目录是哪个？
