### ISSUE TITLE
爬虫爬出来 500 Internal Server Error

### ISSUE THREAD

**Issue by yyc12345** [Aqua-Dream/Tieba_Spider#24]
今天我在尝试用这个程序爬取我自己关注的贴吧的精品帖的时候，一开始都很顺利，但是到最后一页（25页）的时候就卡死了，然后就输出：`2020-07-18 12:00:43 [scrapy.downloadermiddlewares.retry] ERROR: Gave up retrying <GET https://tieba.baidu.com/p/3334670701?red_tag=3462644114> (failed 3 times): 500 Internal Server Error`

然后我直接访问这个帖子链接，打不开，然后我又去贴吧的精品贴的最后一页的html里面查这个连接，也没有匹配。无奈最后我只能Ctrl+C强制关掉了。帖子数据太多我也没核对是不是所有的帖子都被拉下来了。

控制台输出日志下（后半段）：
```
Crawling page 20...
Crawling page 21...
Crawling page 22...
Crawling page 23...
Crawling page 24...
Crawling page 25...
2020-07-18 12:00:43 [scrapy.downloadermiddlewares.retry] ERROR: Gave up retrying
 <GET https://tieba.baidu.com/p/3334670701?red_tag=3462644114> (failed 3 times):
 500 Internal Server Error

[我在这里Ctrl+C了]
```

`config.json`配置：
```json
{
    "DEFAULT_TIEBA": "ballance",
    "MYSQL_PASSWD": "*****",
    "MYSQL_DBNAME": {
        "ballance": "tieba_backups"
    },
    "MYSQL_USER": "*****",
    "MYSQL_HOST": "127.0.0.1",
    "MYSQL_PORT": ****
}
```

环境：

* Python: Python 3.6.0 (v3.6.0:41df79263a11, Dec 23 2016, 07:18:10) [MSC v.1900 32 bit (Intel)] on win32
* beautifulsoup4: 4.9.1
* scrapy: 2.2.1
* mysqlclient: 1.4.6
* mysql: 8.0.17
* OS: Windows Server 2008 R2 Enterpise Services Pack 1 x64

运行的命令：`scrapy run -g`

服务器是tx云

**Comment by Aqua-Dream** [comment]
这个帖子在第17页(精品帖的排序好像是按发帖时间，也就是帖子ID来排序，所以很容易手动找到在哪一页)。

之所以最后一页才出现错误提示，是因为帖子爬取是并行的，17页这个帖子因为一直打不开，优先级被排到了最后。其他的帖子不受影响，比如你可以在数据库查一下post里thread_id=3333888509的帖子，就是排它之后一位的精品帖，应该是存在的。

为什么打不开？应该是百度的BUG，我网页版也打不开，但是手机版是可以的。如果以后能打开了，想要再备份这个帖子，可以输入`scrapy run -g -p 17 17`表示只爬第17页。当然，如果以后精品帖增加了，这个页数可能会变。

**Comment by yyc12345** [comment]
非常感谢 👍 

还想问一下，如果它出现这种`Gave up retrying`，我是不是不需要去用Ctrl+C管它，它最终会自己结束。

14：07补：
试了，可以不用管，问题解决了
