### ISSUE TITLE
有两个问题向您请教

### ISSUE THREAD

**Issue by Kongwhei** [Aqua-Dream/Tieba_Spider#25]
非常感谢您分享的这个爬虫，我也确实有所受益，再次感谢您!
但是很抱歉我刚入门，还有两个问题向您请教下：
1、我爬取的数据只有1000条，三个表都只有1000条。我爬的贴吧一共34页，确实每一页都爬到了，但是只有1000条 我很疑惑，是在哪里设置阈值了吗？还是我操作的问题呢？
2、由于您的代码中没有爬取主贴thread的发帖时间，请问我该如何设置？
期待您的回复！谢谢！

**Comment by Aqua-Dream** [comment]
1. 我没有出现过这种问题，是不是你的数据库默认设置了阈值，或者查询的时候自动选择了limit size? 你试下count(*)也是返回1000么？
2. post中有记录时间，所以去post中查找对应thread_id的一楼的发帖时间即可。

**Comment by Kongwhei** [comment]
> 1. 我没有出现过这种问题，是不是你的数据库默认设置了阈值，或者查询的时候自动选择了limit size? 你试下count(*)也是返回1000么？
> 2. post中有记录时间，所以去post中查找对应thread_id的一楼的发帖时间即可。

非常感谢，已经解决啦~
