### ISSUE TITLE
哥又遇到问题了，大的贴吧帖子多爬到pn值10000以上，帖子开始一种循环，那些老帖是没了吗

### ISSUE THREAD

**Issue by tomyu168** [Aqua-Dream/Tieba_Spider#39]
https://tieba.baidu.com/f?kw=%E7%BD%AA%E6%81%B6%E8%A3%85%E5%A4%87&ie=utf-8&pn=10010

https://tieba.baidu.com/f?kw=%E7%BD%AA%E6%81%B6%E8%A3%85%E5%A4%87&ie=utf-8&pn=0

https://tieba.baidu.com/f?kw=%E7%BD%AA%E6%81%B6%E8%A3%85%E5%A4%87&ie=utf-8&pn=9999

哥你看下，当pn=9999的时候还能看老帖，超过10000就变成首页了，陷入循环，那么那些老帖去哪儿了，怎么获取，感激不尽哥

**Comment by Aqua-Dream** [comment]
打开到pn=10000之后点下一页，照样跳转到首页，说明百度根本就没打算把后面的帖子放出来。我也不知道怎么获取。

**Comment by tomyu168** [comment]
> 打开到pn=10000之后点下一页，照样跳转到首页，说明百度根本就没打算把后面的帖子放出来。我也不知道怎么获取。

哎，白高兴半天，我想怎么后面那么多重复的……还是谢谢哥，百度这魔怔……
