### ISSUE TITLE
mac + anaconda 配置环境和执行

### ISSUE THREAD

**Issue by congcong009** [Aqua-Dream/Tieba_Spider#5]
仓主你好，

我在 anaconda 下配置了你提到的那几样插件（scrapy + mysqlclient + beautifulsoap），版本也高于你的要求，在spyder（python 3.6）中打开了项目，执行就报错，如下：

<img width="525" alt="screen shot 2018-07-09 at 17 13 26" src="https://user-images.githubusercontent.com/2680017/42441725-71e046f4-839b-11e8-8c94-33053e326b73.png">

如果我切换到 iTerm2 中执行，得到的错误如下：
<img width="843" alt="screen shot 2018-07-09 at 17 08 42" src="https://user-images.githubusercontent.com/2680017/42441749-81ee1738-839b-11e8-9e63-d1e1d6babb44.png">

我的数据库 MySQL 是在 XAMPP 中运行，使用Navicat 查看数据库可以看到如下信息
<img width="825" alt="screen shot 2018-07-09 at 17 16 12" src="https://user-images.githubusercontent.com/2680017/42442574-9d120220-839d-11e8-8356-a7c38d35c7cf.png">

那么我的配置文件是
<img width="263" alt="screen shot 2018-07-09 at 17 20 47" src="https://user-images.githubusercontent.com/2680017/42442118-75721c74-839c-11e8-88f3-38de54ea96d1.png">

请问，我现在的问题是什么原因造成的呢？百度了也没找到答案呢，感谢回复。

**Comment by Aqua-Dream** [comment]
您好！
请去掉`config.json`第5行最后一个字符，即讲
```
"草缸": "cg",
```
修改位
```
"草缸": "cg"
```

然后再试试。

**Comment by congcong009** [comment]
感谢回复啊，调整了配置不行。我重新安装了原生的 MySQL for Mac，不适用 XMAPP 的集成容器，爬虫可以正常工作啦，数据库里看到趴下来的内容了，只是在运行的过程中，依然报的错误如下：

<img width="1273" alt="screen shot 2018-07-10 at 13 42 11" src="https://user-images.githubusercontent.com/2680017/42491487-7f91f8ea-8447-11e8-9fb6-3339de1ffda8.png">

**Comment by Aqua-Dream** [comment]
这个问题已经更新解决了，请更新后再试试

**Comment by congcong009** [comment]
咦你更新了哪个文件，log 没看到呢？

**Comment by Aqua-Dream** [comment]
git pull 即可

**Comment by Aqua-Dream** [comment]
请问问题是否已经解决？

**Comment by congcong009** [comment]
解决了哈，十分感谢呢····后来忘回了，不好意思
