### ISSUE TITLE
你好，我运行程序出现错误请求帮助。

### ISSUE THREAD

**Issue by Systempm** [Aqua-Dream/Tieba_Spider#6]
![0121](https://user-images.githubusercontent.com/19610596/44956140-cdecce00-aef1-11e8-9a77-bdab1d085b28.jpg)

**Comment by Systempm** [comment]
我给他改成 rb 就好起来了。这有影响吗？

**Comment by Aqua-Dream** [comment]
我刚刚修复了，就改了下emotion.py文件，试下pull之后能不能用

**Comment by Systempm** [comment]
已经爬上了~ 一会再试一下

**Comment by Systempm** [comment]
大佬 再问你一下 ， 我想爬整个吧的 ，参数是需要怎么打呢 ？　是按页码？还是

**Comment by Aqua-Dream** [comment]
不用加-p参数就可以了

**Comment by Systempm** [comment]
什么也不加 爬出来的数据 严重少于总数的原因是什么 ？另外 爬完没有提示吗？

**Comment by Aqua-Dream** [comment]
爬的过程中有什么提示吗？
程序结束了就是爬完了。

**Comment by Systempm** [comment]
我在重新 实验一下， 第一次出现了 程序长时间不结束，一看数据库里面拿到的总数不变。

**Comment by Aqua-Dream** [comment]
情况如何？没什么问题我就关了

**Comment by Systempm** [comment]
运行结果非常好，可以关了，大佬辛苦了。

**Comment by Systempm** [comment]
运行结果非常好，可以关了，大佬辛苦了。

**Comment by Systempm** [comment]
运行结果非常好，可以关了，大佬辛苦了。

**Comment by Systempm** [comment]
运行结果非常好，可以关了，大佬辛苦了。
