### ISSUE TITLE
百度贴吧帖子数据排序跟爬到的数据不一致

### ISSUE THREAD

**Issue by hjlFrist** [Aqua-Dream/Tieba_Spider#8]
请问下，你这个爬的数据是按照什么排序的？爬到的数据跟贴吧里面帖子数量不一致

**Comment by Aqua-Dream** [comment]
设置了帖子ID作为主键，是按ID排序的。数量不一致是因为贴吧显示的帖子数不准（可能包含了删掉的帖子），可能就是有的帖子因为未知原因爬不了（比如比较久远的帖子可能需要验证码）

**Comment by hjlFrist** [comment]
感谢回复，对了下，几乎都爬到了，数据够用了
