### ISSUE TITLE
楼中楼的没爬全

### ISSUE THREAD

**Issue by Tangzy7** [Aqua-Dream/Tieba_Spider#9]
只能爬到楼中楼的第一页以及没折叠的

**Comment by Aqua-Dream** [comment]
> 只能爬到楼中楼的第一页以及没折叠的

请提供一下没爬全的帖子链接、页码以及一个没爬到的内容例子

**Comment by Tangzy7** [comment]
https://tieba.baidu.com/p/4208637608#80468835459l 三楼爬到“就是玄甲啊，改正常了” 就没了，然后开始同一贴下一个楼中楼的“其它地方也没有啊。”，可以看我mysql的截图，已经按post_id和id排好序的。

**Comment by Tangzy7** [comment]
截图
<img width="714" alt="wx20181118-124724 2x" src="https://user-images.githubusercontent.com/23446696/48668752-2b2b0f80-eb30-11e8-99c4-65207accb44b.png">

**Comment by Tangzy7** [comment]
> > 只能爬到楼中楼的第一页以及没折叠的
> 
> 请提供一下没爬全的帖子链接、页码以及一个没爬到的内容例子

回在原贴了，忘了@你了sorry

**Comment by Tangzy7** [comment]
> > 只能爬到楼中楼的第一页以及没折叠的
> 
> 请提供一下没爬全的帖子链接、页码以及一个没爬到的内容例子

@Aqua-Dream 
回在原帖了，麻烦你看一下。
http://tieba.baidu.com/p/totalComment?tid=%d&fid=1&pn=%d" % (meta['thread_id'], meta['page'])
这句好像只能拿到第一页的没折叠的回复

**Comment by Aqua-Dream** [comment]
感谢指出，看来这是从一开始就有且没被发现的内容。totalComment只加载各个楼中楼第一页的内容，点击下一页的时候会调用xhr再进行拉取。

我暂时还没想好这个问题该怎么处理，如果用comment的链接的话又要写很多代码了……

**Comment by Tangzy7** [comment]
> 感谢指出，看来这是从一开始就有且没被发现的内容。totalComment只加载各个楼中楼第一页的内容，点击下一页的时候会调用xhr再进行拉取。
> 
> 我暂时还没想好这个问题该怎么处理，如果用comment的链接的话又要写很多代码了……
@Aqua-Dream 
 没事，感谢，从你代码学到很多。看来是只能用comment了， BTW，我也是仙迷

**Comment by shimachao** [comment]
> 感谢指出，看来这是从一开始就有且没被发现的内容。totalComment只加载各个楼中楼第一页的内容，点击下一页的时候会调用xhr再进行拉取。
> 
> 我暂时还没想好这个问题该怎么处理，如果用comment的链接的话又要写很多代码了……

我用comment的链接也没爬全

**Comment by JonXia** [comment]
写一个连续点击折叠按钮的功能 然后再爬 可以么

**Comment by shitianshiwa** [comment]
也许这个可以解决，也顺便求帮忙测试下，爬楼中楼是否大多数情况下都是全的，排除隐藏贴的情况
https://github.com/shitianshiwa/BaiduTieBaOffline/blob/0.11/get_single_thread.py

**Comment by SeekerDexter** [comment]
我这边用下来发现，不仅是楼中楼有缺失，帖子的回复也有缺失。比如爬取这个[帖子](https://tieba.baidu.com/p/6635625221)，thread表中可以找到该数据，显示有92条回复，但是`select count(1) from post where thread_id = 6635625221`结果是0

**Comment by Aqua-Dream** [comment]
> 我这边用下来发现，不仅是楼中楼有缺失，帖子的回复也有缺失。比如爬取这个[帖子](https://tieba.baidu.com/p/6635625221)，thread表中可以找到该数据，显示有92条回复，但是`select count(1) from post where thread_id = 6635625221`结果是0

可能是网络波动，可以多爬几次。我这边试了下是有的。
![image](https://user-images.githubusercontent.com/17526818/84854558-87e80680-b094-11ea-8ef6-b59cbcba735d.png)

**Comment by SeekerDexter** [comment]
> > 我这边用下来发现，不仅是楼中楼有缺失，帖子的回复也有缺失。比如爬取这个[帖子](https://tieba.baidu.com/p/6635625221)，thread表中可以找到该数据，显示有92条回复，但是`select count(1) from post where thread_id = 6635625221`结果是0
> 
> 可能是网络波动，可以多爬几次。我这边试了下是有的。
> ![image](https://user-images.githubusercontent.com/17526818/84854558-87e80680-b094-11ea-8ef6-b59cbcba735d.png)

我昨晚与今天在不同的网络下爬取了多次，都是一样的没有，但是结合您的测试，就比较奇怪，我再换个环境实施吧。
